i3/urls.py
from django.conf.urls import url
from . import views

app_name = 'i3'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^wc/$', views.wc, name='wc'),
    url(r'^cockpit/$', views.cockpit, name='cockpit'),
    url(r'^engine/$', views.engine, name='engine'),
    url(r'^status/$', views.status, name='status'),
    url(r'^cooling_switch/$', views.cooling_switch, name='cooling_switch'),
    url(r'^set_gps/(?P<gps_coords>[0-9]+)/$', views.set_gps, name='set_gps'),
    url(r'^itinerary/$', views.itinerary, name='itinerary'),
    url(r'^ftl_on/$', views.ftl_on, name='ftl_on'),
    url(r'^pump_oxygen/$', views.pump_oxygen, name='pump_oxygen'),
    url(r'^move_fuel/$', views.move_fuel, name='move_fuel'),
    url(r'^enter_fuel/$', views.enter_fuel, name='enter_fuel'),
    url(r'^game_over/$', views.game_over, name='game_over'),
]

isolatedIntergalacticIncident/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('i3.urls')),
    url(r'^admin/', admin.site.urls),
]

i3/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import random

Planets = ["648721","876194","846721","427619","465973","321678","976382","346197","276481","000000"]

# Create your models here.

class Ship(models.Model):

    planet = models.IntegerField(default=0)
    distance_to_planet = models.FloatField(default=10000)
    health = models.FloatField(default=1000)
    multiplier = models.FloatField(default=0.1)
    oxygen = models.FloatField(default=100)
    heat = models.FloatField(default=50)
    cooling = models.BooleanField(default=True)
    engine_fuel = models.FloatField(default=0)
    fuel = models.FloatField(default=100)
    current_shield = models.IntegerField(default=0)
    ideal_shield = models.IntegerField(default=0)
    shield_instability = models.FloatField(default=0)
    gps = models.CharField(max_length=6, default='000000')
    self_destruct = models.BooleanField(default=False)
    ftl_on = models.BooleanField(default=False)

    def update(self):
        health_loss = 1

        if self.oxygen > 0:
            self.oxygen -= self.multiplier
        else:
            self.health -= health_loss


        if self.fuel > 0 and self.ftl_on:
            self.fuel -= .5
        else:
            self.ftl_on = False

        if abs(self.heat) > 100:
            self.health -= health_loss
        if self.cooling:
            self.heat -= self.multiplier
        else:
            self.heat += self.multiplier


        if self.distance_to_planet < 1:
            self.planet += 1
            self.distance_to_planet = 10000
            self.multiplier *= 2
            self.health += 100

        if self.ftl_on:
            if self.gps == Planets[self.planet]:
                self.distance_to_planet -= 10 + random.randint(1,100)
            else:
                self.distance_to_planet += random.randint(-20,20)

        self.shield_instability += self.multiplier
        if random.randint(0,200) < self.shield_instability:
            self.ideal_shield = random.randint(5,95)
            self.shield_instability = 0

        if (self.current_shield + 10 > self.ideal_shield and self.current_shield - 10 < self.ideal_shield):
            self.health -= health_loss

    def switch_cooling(self):
        self.cooling = not self.cooling

i3/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse
from django.utils import timezone
from django.views.generic import TemplateView

from models import Ship
from django.shortcuts import render

Current_Ship = 10

# Create your views here.
def index(request):
    template = 'i3/index.html'
    return render(request,template)


def wc(request):
    template = 'i3/wc.html'
    return render(request,template)


def cockpit(request):
    template = 'i3/cockpit.html'
    return render(request,template)


def engine(request):
    template = 'i3/engine.html'
    return render(request,template)


def status(request):
    ship, created = Ship.objects.get_or_create(pk= Current_Ship)
    ship.update()
    shield = ship.ideal_shield == ship.current_shield
    ship.save()
    template = 'i3/status.html'
    return render(request,template,{'Ship': ship,'Shield':shield})


def cooling_switch(request):
    ship = Ship.objects.get(pk=Current_Ship)
    ship.switch_cooling()
    ship.save()
    return HttpResponse(str(ship.cooling))


def set_gps(request,gps_coords):
    ship = Ship.objects.get(pk=Current_Ship)
    ship.gps = gps_coords
    ship.save()
    return HttpResponse('BUENO')


def itinerary(request):
    template = 'i3/itinerary.html'
    return render(request,template)


def ftl_on(request):
    ship = Ship.objects.get(pk=Current_Ship)
    ship.ftl_on = True
    ship.save()
    return HttpResponse('BUENO')


def pump_oxygen(request):
    ship = Ship.objects.get(pk=Current_Ship)
    if ship.oxygen < 150:
        ship.oxygen += 1
    ship.save()
    return HttpResponse('BUENO')


def move_fuel(request):
    ship = Ship.objects.get(pk=Current_Ship)
    ship.engine_fuel += 1
    ship.save()
    return HttpResponse('BUENO')


def enter_fuel(request):
    ship = Ship.objects.get(pk=Current_Ship)
    if ship.engine_fuel > 0:
        ship.engine_fuel -= 1
        ship.fuel += 1
    ship.save()
    return HttpResponse('BUENO')


def game_over(request):
    template = 'i3/game_over.html'
    return render(request, template)

i3/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<meta charset="UTF-8">

<head>
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <title>{% block title %}Isolated Intergalactic Incident  {% endblock %}</title>
</head>

<body style="background-image:url( {% static 'space1.jpeg' %});  background-size: 1920px 1080px;
    background-repeat: no-repeat;">

 <script type="text/javascript" src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

<script type="text/javascript">
    setInterval(function()
{
    $.ajax({
      type:"get",
      url:"{% url 'i3:status'%}",
      datatype:"html",
      success:function(data)
      {
          document.getElementById("status").innerHTML = data;
      }
    });
}, 1000);

    function asy(place){
        $.ajax({
      type:"get",
      url:"/"+place+"/",
      datatype:"html",
    });
    }
</script>


    <div id="header" class="center">
        {% block sidebar %}
        <h1>I3</h1>
        {% endblock %}
    </div>

    <div id="content" class="center">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/i3/cockpit.html
{% extends "base.html" %}
{% load staticfiles %}

{%block content%}
    <h1>COCKPIT</h1>
<link rel="stylesheet" href="{% static 'pump.css' %}" />
    <div style="float: right;" id="status"></div>
 <div style="margin:5%">
    <input id="gps" name="gps" type="text" value="000000">
    <button onclick="asy('set_gps/' + document.getElementById('gps').value)">ENTER GPS COORDS</button><a href="{% url 'i3:itinerary' %}"><button>Itinerary</button></a>
</div>
    <div>



<div id="volumebar">
  <div id="volume"></div>
</div>
<div id="display"></div>
<div id="indicator">0</div>
<div id="target" class="bar"></div>

    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.js"></script>
    <script type="text/javascript" src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src = "{% static 'pump.js' %}"></script>

        <span style=" position: absolute; bottom: 20px; left: 200px;"> OXYGEN PUMP </span>
    </div>
    <button style ="margin: 5%  " onclick="asy('move_fuel')">MOVE FUEL TO ENGINE ROOM</button>
    <div style ="margin: 5%  " id="slidecontainer">
        <span>Shield frequency: <span id = "output"></span></span>
        <input type="range" min="0" max="100" value="50" id="myRange">
    </div>
    <script type="text/javascript">
        var slider = document.getElementById("myRange");
        var output = document.getElementById("output");
        slider.oninput = function() {
            asy("set_shield/"+this.value)
            output.innerHTML = this.value;
            }
    </script>
{%endblock%}

templates/i3/engine.html
{% extends "base.html" %}
{% load staticfiles %}

{%block content%}
    <link rel="stylesheet" href="{% static 'ftl_crank2.css' %}" />
    <div style="float: right;" id="status"></div>
    ENGINE
    <div style ="margin: 5%  ">Cooling:
        <!-- Rectangular switch -->
        <label class="switch" onclick="asy('cooling_switch')">
          <input type="checkbox">
          <span class="slider"></span>
        </label>
    </div>



    <div style ="margin: 5%; margin-left: 15%;  ">
 FTL
    <div id="volumeBarHolder">
        <div id="volumeBar"></div>
            </div><div>
  <img id="wheel" src="https://image.ibb.co/ivFeFv/handle2.png" />
    </div>
        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.19.0/utils/Draggable.min.js"></script>
        <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/gsap/1.19.0/TweenMax.min.js"></script>


        <script type="text/javascript" src="{% static 'ftl_crank2.js' %}"></script>
    </div>
    <button onclick="asy('enter_fuel')">MOVE FUEL TO FTL_DRIVE</button>

{%endblock%}

templates/i3/game_over.html
{% extends "base.html" %}

{%block content%}
    <h1 style="color: white; text-align: center; ">Game OVER!</h1>
    <p style="color: white; text-align: center; ">You have perished in the vaccum of space, as you slowly fade of your thoughts drift
    to space vegas and how you wish you were in that escape pod!</p>
    <div style="text-align: center" class = "button">
       <a href="{% url 'i3:index' %}"><button type="button">Restart</button> </a>
    </div>
{%endblock%}

templates/i3/index.html
{% extends "base.html" %}

{%block content%}
    <h1 style="color: white; text-align: center; ">Welcome to Isolated Intergalactic Incident!</h1>
    <p style="color: white; text-align: center; ">Your crew has abandoned you and taken the only escape pod
    to space vegas. You are alone with only your wits to get you home.
    Single-handedly get yourself back to Earth</p>
    <div style="text-align: center" class = "button">
       <a href="{% url 'i3:wc' %}"><button type="button">Begin</button> </a>
    </div>
{%endblock%}

templates/i3/itinerary.html
{% extends "base.html" %}

"648721","876194","846721","427619","465973","321678","976382","346197","276481","000000"
{%block content%}
    <span class="noselect">
    <p class="noselect">Iasmoater:648721</p>
    <p class="noselect">Zepluapra:876194</p>
    <p class="noselect">Yeshillon:846721</p>
    <p class="noselect">Usmyke:846721</p>
    <p class="noselect">K-888:427619</p>
    <p class="noselect">Treasure Planet:465973 </p>
    <p class="noselect">Flobizor-15:321678</p>
    <p class="noselect">The Planet of ETERNAL Torture, Pain, and Suffering. Sponsored by Gemshlon Spacesuits, You're Always Safe With a Gemshlon tm:976382</p>
    <p class="noselect">5:346197</p>
    <p class="noselect">Broop Kidron 15:276481</p>
    <p class="noselect">Earth:000000</p>
    <a href="{% url 'i3:cockpit' %}"><button>Return</button></a>
    </span>
{%endblock%}

templates/i3/status.html
{% load staticfiles %}

    <!--Distance to Planet-->
    <p>At planet: {{ Ship.planet }}</p>
    <p>Distance to next planet: {{ Ship.distance_to_planet }}</p>

    <!--HEALTH-->
    <p>{% if Ship.health >= 800 %}
    <img src="{%  static 'green-light.png' %}">
        {% endif %}
        {% if Ship.health <= 800 and Ship.health >= 400%}
        <img src="{% static 'yellow-light.png' %}">
        {% endif %}
        {% if Ship.health <= 400 %}
        <img src="{% static 'red-light.png' %}">
        {% endif %}

        {% if Ship.health <= 0 %}
            <script type="text/javascript"> window.location = ({% url 'i3:game_over' %}</script>
        {% endif %}
        Health {{  Ship.health }}</p>


    <!--OXYGEN-->
    <p>{% if Ship.oxygen >= 80 %}
    <img src="{%  static 'green-light.png' %}">
        {% endif %}
        {% if Ship.oxygen <= 80 and Ship.oxygen >= 40%}
        <img src="{% static 'yellow-light.png' %}">
        {% endif %}
        {% if Ship.oxygen <= 40 %}
        <img src="{% static 'red-light.png' %}">
        {% endif %}Oxygen {{  Ship.oxygen }}</p>


    <!--HEAT-->
    <p>{% if Ship.heat >= -25 and Ship.heat <= 25 %}
    <img src="{%  static 'green-light.png' %}">
        {% endif %}
        {% if Ship.heat <= -25 or Ship.heat >= 25%}
        <img src="{% static 'yellow-light.png' %}">
        {% endif %}
        {% if Ship.oxygen <= -75 or Ship.heat >= 75  %}
        <img src="{% static 'red-light.png' %}">
        {% endif %}Heat {{ Ship.heat }}</p>


    <!-- Fuel-->
    <p>{% if Ship.fuel >= 80 %}
    <img src="{%  static 'green-light.png' %}">
        {% endif %}
        {% if Ship.fuel <= 80 and Ship.fuel >= 40%}
        <img src="{% static 'yellow-light.png' %}">
        {% endif %}
        {% if Ship.fuel <= 40 %}
        <img src="{% static 'red-light.png' %}">
        {% endif %}Fuel {{ Ship.fuel }}</p>

    <!--FTL-->
    <p>{% if Ship.ftl_on == True %}
    <img src="{%  static 'green-light.png' %}">
        {% endif %}
        {% if Ship.ftl_on == False %}
        <img src="{% static 'red-light.png' %}">
        {% endif %}FTL </p>

    <!--SHIELD-->
    <p>{% if Shield == True %}
    <img src="{%  static 'green-light.png' %}">
        {% endif %}
        {% if Shield == False %}
        <img src="{% static 'red-light.png' %}">
        {% endif %}Shield - Ideal Frequency: {{ Ship.ideal_shield }} </p>

templates/i3/wc.html
{% extends "base.html" %}

{%block content%}
    <div class = "button" style="color: white;"> <form>
  <input type="radio"  onclick="myFunction(this.value)" name="room" value="cockpit" id="myRoom"> Cockpit<br>
  <input type="radio" onclick="myFunction(this.value)" name="room" value="engine_bay" id="myRoom"> Engine Bay<br>

  <script>
function myFunction(val) {

    if(val == "cockpit"){
        window.location = ({% url 'i3:cockpit' %})
        console.log("Cockpit Selected")
    }
    else if(val == "engine_bay"){

        console.log("Engine Bay Selected")
        window.location = ({% url 'i3:engine' %})
    }

}
</script>


</form>

{%endblock%}